[package]
name = "calendar-puzzle-web"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1"
rayon = "1.8"

[profile.release]
lto = "fat"
codegen-units = 1
incremental = false
panic = "abort"